[package]
name = "itron"
version = "0.1.0"
authors = [
    "Tomoaki Kawada",
]
license = "MIT OR Apache-2.0"
edition = "2018"
readme = "src/lib.md"
description = "Interface to operating systems based on Î¼ITRON or its derivative."
categories = ["embedded", "no-std", "external-ffi-bindings", "os"]
repository = "https://github.com/kawadakk/itron-rs"

[features]
default = []
nightly = ["doc_cfg"]
doc_cfg = []
unstable = []

# --------------------------------------------------------
# Kernel selection
none = ["dcre", "rstr_task"]
asp3 = []

# --------------------------------------------------------
# Kernel customization

# Dynamic object creation. Enables owned wrapped types.
dcre = []

# "Restricted" tasks
rstr_task = []

[dependencies]


[package.metadata.docs.rs]
# arbitrarily choose ASP3.
features = ["doc_cfg", "nightly", "unstable", "asp3", "dcre"]
# only build the default target
targets = []
