[package]
name = "itron"
version = "0.0.0"
edition = "2018"
publish = false

[features]
default = []
nightly = ["doc_cfg"]
doc_cfg = []

# --------------------------------------------------------
# Kernel selection
none = ["dcre", "rstr_task"]
asp3 = []

# --------------------------------------------------------
# Kernel customization

# Dynamic object creation. Enables owned wrapped types.
dcre = []

# "Restricted" tasks
rstr_task = []

[dependencies]


[package.metadata.docs.rs]
features = ["doc_cfg"]
