name: CI

on:
  push:

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - { features: "none" }

          # TOPPERS/ASP3
          - { features: "asp3" }
          - { features: "asp3,rstr_task" }
          - { features: "asp3,messagebuf" }
          - { features: "asp3,ovrhdr" }
          - { features: "asp3,subprio" }
          - { features: "asp3,pi_mutex" }
          - { features: "asp3,rstr_task,messagebuf,ovrhdr,subprio,pi_mutex" }
          - { features: "asp3,dcre" }
          - { features: "asp3,dcre,rstr_task" }
          - { features: "asp3,dcre,messagebuf" }
          - { features: "asp3,dcre,ovrhdr" }
          - { features: "asp3,dcre,subprio" }
          - { features: "asp3,dcre,pi_mutex" }
          - { features: "asp3,dcre,rstr_task,messagebuf,ovrhdr,subprio,pi_mutex" }
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features ${{ matrix.features }}

